import { Sidebar } from "./SideBar/page";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex w-full">
      <Sidebar />
      <main className="flex-grow bg-gray-100 p-4">{children}</main>
    </div>
  );
}
